project_id = "scptdrovaomhbrbzbkgf"

[functions.create-pix]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.send-remarketing]
verify_jwt = false

[functions.remarketing-cron]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.send-promotion]
verify_jwt = false

[functions.daily-promotion-cron]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.claim-free-trial]
verify_jwt = false
